### ISSUE TITLE
Failed install for Magento 2.4.5

### ISSUE THREAD

**Issue by 7LlantasManager** [developersalliance/module-table-rates#1] opened 2023-07-19 16:04 UTC
In the process of upgrade class, sudo php bin/magento se:up fails with this error:

Errors during compilation:
        DevAll\TableRates\Ui\Component\FormDataProvider
                Incompatible argument type: Required type: string. Actual type: \DevAll\TableRates\Ui\Component\name; File: 
/bitnami/magento/vendor/developersalliance/module-table-rates/Ui/Component/FormDataProvider.php

Total Errors Count: 1

**Comment by davidtabat** [comment] 2023-07-19 17:00
@7LlantasManager I am setting up clean magento 2.4.5 instance to replicate the issue, will let you know when there will be updates.

**Comment by davidtabat** [comment] 2023-07-19 17:04
also, could you specify which php version do u ran on?

**Comment by davidtabat** [comment] 2023-07-19 17:18
issue confirmed, fix will be released in several minutes - thank you for the feedback!!

**Comment by 7LlantasManager** [comment] 2023-07-19 17:21
Thanks for your work, this module is fully functionally.

**Comment by davidtabat** [comment] 2023-07-19 17:30
Released version 1.0.3 . It should be good now.

**Comment by davidtabat** [comment] 2023-07-19 17:30
Released version 1.0.3 . It should be good now.

**Comment by 7LlantasManager** [comment] 2023-07-19 17:32
I'm test now

**Comment by 7LlantasManager** [comment] 2023-07-19 17:39
Installs works perfect! Nice Work. But I'm open the module and shows that:

Not registered handle tablerates_view_grid_data_source

I'm have already registered some shipping rates. But don't show.

**Comment by davidtabat** [comment] 2023-07-20 05:27
I didn't manage to replicate the bug.
if you are in production mode - also run setup:di:compile
I realized the new version with the updated di.xml, (on some systems new line in the argument name value doesn't work so I remove the new line, so it could be that this was the cause for u as well)

**Comment by davidtabat** [comment] 2023-07-20 09:29
Let me know if this fixed the issue or not.

**Comment by 7LlantasManager** [comment] 2023-07-20 15:16
It works!. Thank you.

**Comment by davidtabat** [comment] 2023-07-20 15:48
You are welcome, Thank you very much for the very first open issue - we appreciate your contribution.

**Closed as completed by davidtabat** 2023-07-20 15:48 UTC
